
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrjgmxccpidpsptamomd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyamdteGNjcGlkcHNwdGFtb21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTE2MzYsImV4cCI6MjA2MTIyNzYzNn0.2CFUbpanf90sccAKwcqrQycgNm78tokpqjugQiV26Sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});
