// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmufxhvetbfeajerango.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdWZ4aHZldGJmZWFqZXJhbmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzkxMzgsImV4cCI6MjA2MTE1NTEzOH0.dAmdrqXRk6k2bWTsufzbfjruICMX-DctRJG-xN-KeoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);