// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://katabukixlrkvwgglvgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthdGFidWtpeGxya3Z3Z2dsdmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDA1MjEsImV4cCI6MjA2MTExNjUyMX0.mJe0dDyIFgpfbWLkFMWo4mlb7CZScbFWU5TB5kkSEXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);